# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 278dff8a7f28d841cd0981ac08cb5a5086dfae6a8c42d2296295e4d1404324ce32af0a93e7d92122827f9ec6bec3877c236cb4f35cca4e415c2c2fe553b49634

test:
  secret_key_base: 42bda76364014f04536f06f81da2c7613f3531fa83a16100c5fd31000c6156d2fa1fb3a5327b37dd594a17213d35b77b880863afff3a62fb2b4b53fad862343f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
